### PR TITLE
Revamp for Julia v0.6

### LINKED ISSUE #65: Julia v0.6 Support?
Is this currently working in Julia v0.6?  I notice that v0.6 is not in CI.  I am currently getting this message,

```
ERROR: LoadError: MethodError: no method matching setsolver(::JuMP.Model, ::AmplNLWriter.AmplNLSolver)
The applicable method may be too new: running in world age 21832, while current world is 21843.
```
@jac0320, @kaarthiksundar do you two have similar issues?

### LINKED ISSUE #67: Better error message when solver crashes
If a solver crashes AmplNLWriter errors with the slightly unhelpful message `ERROR: SystemError: opening file /path/to/temp/file.sol: No such file or directory`

Ref https://github.com/JuliaOpt/AmplNLWriter.jl/issues/59, https://github.com/JuliaOpt/AmplNLWriter.jl/issues/55, https://github.com/JuliaOpt/AmplNLWriter.jl/issues/20

### LINKED ISSUE #69: CodeCov
Any reason not to set this up?

### PR DESCRIPTION
**Pull request by odow**
*This PR should probably be split into some smaller ones*

### Allowing .sol files to be read from an IO stream

I'm playing around with the NL file-format interface to NEOS (ref https://neos-server.org/neos/solvers/milp:CPLEX/NL.html and https://github.com/odow/NEOS.jl/issues/17).

I made some changes so I can read the .sol file from a stream instead of having to write the file to disk.

### Changed tests to `@testset`

I've also removed CoinOptServices from the testing suite as it needs some work and was causing failures on my windows machine.

### Dumping the XXXNLSolver
I've removed `BonminNLSolver`, `CouenneNLSolver`, and `IpoptNLSolver` (and therefore the conditional dependencies) in favour of forcing the user to explicitly construct the solvers.

```julia
using AmplNLWriter
solver = IpoptNLSolver()
```
becomes
```julia
using AmplNLWriter, Ipopt
solver = AmplNLSolver(Ipopt.amplexe)
```
which is a bit more clear and less magical about what is actually occuring. 

**This is a hard breaking change for current users.**

Hopefully this fixes #65 

Todo before merge
 - [x] update README
 - [x] update JuMP solver table

### Removed support for v0.5
<s>This uses Julia v0.6 syntax (`.!`) but doesn't change the REQUIRE yet so still todo:
 - [ ] fix deprecation properly by bumping version or using compat</s>

Closes #64 

### Better error message

If a solver crashes without producing a `.sol` file the user gets a slightly more helpful error message. Closes #67 

### Added codecov

Closes #69

### CODE REVIEW

**Comment by mlubin** [comment]
Please drop 0.5!

**Comment by odow** [comment]
I might put some effort into sorting out the tests while I'm at it.

File: src/AmplNLWriter.jl [hunk 1]
```diff
@@ -23,31 +23,58 @@ immutable AmplNLSolver <: AbstractMathProgSolver
...
                       filename::String="")
     AmplNLSolver(solver_command, options, filename)
 end
 
 function BonminNLSolver(options=String[]; filename::String="")
-    osl || error("CoinOptServices not installed. Please run\n",
-                 "Pkg.add(\"CoinOptServices\")")
-    AmplNLSolver(CoinOptServices.bonmin, options; filename=filename)
+    error("""
+        BonminNLSolver is no longer available by default through AmplNLWriter.
```
Comment (mlubin) [inline src/AmplNLWriter.jl]: This is a big breaking change and needs corresponding updates to the README and JuMP's solver table.

Comment (odow) [reply src/AmplNLWriter.jl]: Yeah I'm not planning on merging this any time soon. Just trying it out. Yay/Nay on whether this is a good idea?

Comment (mlubin) [reply src/AmplNLWriter.jl]: Go for it. This dependency is very flaky.

**Comment by odow** [comment]
This is probably ready to be merged. 

Once it is merged, I might go through and have another tidy up. Then we should tag a new version in METADATA and merge the JuMP PR to reflect the changes in the solver table.

**Comment by odow** [comment]
Merging this so that we can make progress with other PRs. Cc @ccoffrin
